### ISSUE TITLE
Improve data fetching upon form resubmission

### ISSUE THREAD

**Issue by parth-io** [usdevs/usc-website-hackathon-frontend#110]
Currently, we call `mutateUsers()` or `mutateOrgs()` after submitting a form to refresh the data on the frontend. However, this is fetches all the data again and not just the data from the updated form.

useSwr has a whole bunch of settings and tunings for an optimistic UI and to fetch only the required data, but could not get it to work previously.

**Comment by zsh-eng** [comment]
Closing this issue as we react query takes care of that for us. See #198
