### ISSUE TITLE
[Bug] Edit button not working for Admin page

### ISSUE THREAD

**Issue by SeekSaveServe** [usdevs/usc-website-hackathon-frontend#112]
When there are no IG heads, it seems that the edit button breaks
![Screenshot_3](https://github.com/usdevs/usc-website-hackathon-frontend/assets/53963433/efd3b68f-8919-442f-a794-e1596f169385)

Some IGs experiencing this:
NUSC Productions
NUSC Volleyball

**Comment by parth-io** [comment]
Fixed by assigning a temporary IG head - the seed file did not always specify one
