### ISSUE TITLE
Bookings Page: Day View

### ISSUE THREAD

**Issue by parth-io** [usdevs/usc-website-hackathon-frontend#30]
- [x] Day Page: Colour code bookings, another differentiated colour for personal booking ← only if you’re logged in
- [x] After refresh, greyout time cells become normal but remain unselectable - cannot replicate
- [x] Toggle for Day/Month view can be more intuitive - write 'Day', 'Month' for toggle
- [x] Improve displays of details on booking cells - font colour, size, overflow
- [x] Display more details on hover(?)
- [x] TRB is still cut out when the display is at 100% (need to zoom out to see it) - from MC testing
- [x] Possible to add UI changes to make the error message in the booking form more distinct? Low effort fix would be to just make the error message red and bold.  
- [x] When clicked on "Confirm Booking", make the button unselectable or show a processing spinner while the backend processes the request, to prevent duplication of requests to backend
- [x] try to limit the rgb values such that only lighter and brighter colors are generated --> a couple of third party libraries already do this

**Comment by zsh-eng** [comment]
Added loading spinner for creating and deleting bookings.
Fix color generation.

**Comment by parth-io** [comment]
We can do the loading spinner thing after log-in as well, because there is a period of time (1 or 2 seconds) when the Telegram API is processing the request

**Comment by zsh-eng** [comment]
Are you referring to this login button? 
![Image](https://github.com/usdevs/usc-website-hackathon-frontend/assets/49238630/a701056f-4cb6-466f-ba96-41aec5d43b86)
