### ISSUE TITLE
Profile deployment

### ISSUE THREAD

**Issue by parth-io** [usdevs/usc-website-hackathon-frontend#71]
- [x] RAM usage probably keeps increasing on client - to verify this, and if true, where is the memory leak?
- [x] Why does deployment keep restarting
- [ ] Reduce build size with dynamic imports - check tree-shaking
- [ ] Check network usage stats - for admin tab, do not load data for users  immediately
- [ ] See if we can use React Suspense or React.lazy()
- [x] DO docs - check that we are running the build and not dev - why is the TLS warning there
- [x] Set up aleart for restarts

**Comment by parth-io** [comment]
This was an insanely stupid issue to debug. What happened was that the Next.JS at v13 did not work well with Node v16 or below, and DO was at Node v16. Using a Docker container with Node v20 and Next v13.

Also, switched to alpine-linux image because of `musl` libs - apparently, NextJS's `sharp` image optimiser works terribly with Debian's `glibc` or `jmalloc`

**Comment by zsh-eng** [comment]
Closing this issue as we haven't faced any problems with deployment since then.
